### PR TITLE
Allow to copy and slice Bytecode

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Currently copying/slicing a Bytecode/ConcreteBytecode object produces a normal list making some manipulations painful to perform in a natural way. This make copy and slicing type stable. I found it quite valuable to port a project that was using byteplay in the past.

It also adds a `legalize` method to Bytecode/ConcreteBytecode/BasicBlock/ControlFlowGraph which validates the instruction and remove SetLineno meta instructions.

@thautwarm @serhiy-storchaka if you can have a look it would be great.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I will merge on Wed 29th if there ie no  objection. I would like to make a release shortly after. @thautwarm are you still planning a PR for handling the constants issue ? and if yes do you have a timelime ?

**Comment by thautwarm** [comment]
Hi, thanks for this notification! There is a deadline for me on Thursday morning, and I have to prepare for that. 
Could you slightly delay the date of release? I can focus on the PR on Thursday night.

**Comment by MatthieuDartiailh** [comment]
Sure no problem.

**Comment by thautwarm** [comment]
Hi, I'm in an interview. The PR plan is in the highest priority then, will do it a few hours later.

**Comment by MatthieuDartiailh** [comment]
Sure no rush. I am fine releasing sometimes next week.

**Pull request merged**
